### ISSUE TITLE
Adding smaller remote datasets to master catalog and not the pangeo cloud

### ISSUE THREAD

**Issue by aaronspring** [pangeo-data/pangeo-datastore#113]
I started a similar repo about remote URL datasets inspired by this repo: https://github.com/aaronspring/remote_climate_data/
This includes observations like GISTEMP ERSST, HadCRUT4, and the like. Everything below 1GB.

Then after reaching out to twitter, @jhamman suggested to contribute these catalog entries rather to the pangeo master catalog.

So the issue is not about adding new data to the pangeo cloud, but rather adding more datasets to the pangeo catalog.

example with `fsspec.simplecache` and a predefined plot.
```yaml
plugins:
  source:
    - module: intake_xarray

sources:
  HadCRUT4:
    description: HadCRUT temperature anomalies wrt. 1960-1989
    metadata:
      url: https://crudata.uea.ac.uk/cru/data/temperature/
      doi: 10.1029/2011JD017187
      plots:
        temperature_anomaly_over_time:
          title: HadCRUT4 temperature anomly wrt. 1960-1989
          kind: contourf
          x: longitude
          y: latitude
          z: temperature_anomaly
          groupby: time
          cmap: RdBu_r
          levels: 20
          # clim: (-10, 10)  # once https://github.com/holoviz/hvplot/pull/492 is merged
    driver: netcdf
    args:
      urlpath: simplecache::https://crudata.uea.ac.uk/cru/data/temperature/HadCRUT.4.6.0.0.median.nc
      chunks: {'time': 'auto'}
      xarray_kwargs:
        use_cftime: True
```
