### ISSUE TITLE
Required and optional metadata for catalog entries

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo-datastore#19]
I'd like to define some required and recommended intake metadata entries. For now, these are distinct from the dataset attributes (e.g. [ACDD](http://wiki.esipfed.org/index.php/Attribute_Convention_for_Data_Discovery_1-3)) which describe the actual contents. I would like the intake catalog to tell us about the provenance of the cloud-based dataset.

Here's what a current entry looks like:
```yaml
  sea_surface_height:
    description: sea-surface altimetry data from The Copernicus Marine Environment
    metadata:
      url: 'http://marine.copernicus.eu/services-portfolio/access-to-products/?option=com_csw&view=details&product_id=SEALEVEL_GLO_PHY_L4_REP_OBSERVATIONS_008_047'
      tags:
        - ocean
        - satellite
    driver: zarr
    args:
      urlpath: gcs://pangeo-data/dataset-duacs-rep-global-merged-allsat-phy-l4-v3-alt
      storage_options:
        token: anon
      consolidated: True
```

I would propose adding the following **required** field to the metadata:
- _uploader_github_: github handle of whoever uploaded the dataset
- _uploader_email_: email address of whoever uploaded the dataset

In addition, it would be nice to also have the following
- _origin_url_: A link to the "original" source dataset

My goal is to start keeping better track of what we have.

Thoughts @naomi-henderson and @charlesbluca?
